language: node_js
node_js:
- '5'
services:
- redis
addons:
  code_climate:
    repo_token: e82c6dd8a56ba5a3ef81f3398716c64b583dfa0e81e81b13417e415e72bf34ea
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  - CXX=g++-4.8
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
after_success:
- bash <(curl -s https://codecov.io/bash)
